INSERT INTO Bus (bus_id, type_id, description, price, occupancy_status)
VALUES (101, 'DXL', 'Deluxe Bus with maximum capacity of 60 people', 2000, 1);

INSERT INTO Bus (bus_id, type_id, description, price, occupancy_status)
VALUES (102, 'SDX', 'Super Deluxe Bus with amazing window view and capacity of 55 people', 3000, 0);

INSERT INTO Bus (bus_id, type_id, description, price, occupancy_status)
VALUES (103, 'SDX', 'Super Deluxe Bus with amazing window view and capacity of 55 people', 3000, 1);

INSERT INTO Bus (bus_id, type_id, description, price, occupancy_status)
VALUES (104, 'DXL', 'Deluxe Bus with maximum capacity of 60 people', 2000, 0);

INSERT INTO Bus (bus_id, type_id, description, price, occupancy_status)
VALUES (105, 'NAC', 'Normal Bus with basic features like TV and AC', 1500, 1);

INSERT INTO Bus (bus_id, type_id, description, price, occupancy_status)
VALUES (201, 'NAC', 'Normal Bus with basic features like TV and AC', 1500, 0);

INSERT INTO Bus (bus_id, type_id, description, price, occupancy_status)
VALUES (202, 'NAC', 'Normal Bus with basic features like TV and AC', 1500, 0);

INSERT INTO Bus (bus_id, type_id, description, price, occupancy_status)
VALUES (203, 'NOL', 'Normal Bus with no AC', 1250, 1);

INSERT INTO Bus (bus_id, type_id, description, price, occupancy_status)
VALUES (204, 'NOL', 'Normal Bus with no AC', 1250, 0);

INSERT INTO Bus (bus_id, type_id, description, price, occupancy_status)
VALUES (205, 'PRM', 'Primary Budget Bus for 60 people', 1000, 1);